# Generated by Django 5.2.8 on 2025-11-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('calorias', models.IntegerField()),
                ('proteinas', models.IntegerField()),
                ('grasas', models.IntegerField()),
                ('carbohidratos', models.IntegerField()),
                ('sodio', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
