# Generated by Django 5.2.8 on 2025-11-27 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DietaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=100.0, help_text='Cantidad en gramos')),
                ('unidad', models.CharField(default='g', max_length=20)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion.alimento')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion.dieta')),
            ],
            options={
                'unique_together': {('dieta', 'alimento')},
            },
        ),
        migrations.AddField(
            model_name='dieta',
            name='alimentos',
            field=models.ManyToManyField(related_name='dietas', through='nutricion.DietaAlimento', to='nutricion.alimento'),
        ),
    ]
