# Generated by Django 5.2.8 on 2025-11-29 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0002_dieta_dietaalimento_dieta_alimentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('direccion_residencial', models.CharField(max_length=200)),
                ('numero_telefono', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='alimento',
            name='agua_humedad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alimento',
            name='azucares_totales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alimento',
            name='fibra_alimentaria',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MotivoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField()),
                ('motivo', models.TextField()),
                ('objetivos_peso', models.CharField(choices=[('P', 'Pérdida de peso'), ('M', 'Mantenimiento del peso actual'), ('A', 'Aumento de peso'), ('O', 'Otro')], help_text='Objetivos de peso', max_length=200)),
                ('condiciones_patologicas', models.CharField(choices=[('D', 'Diabetes'), ('H', 'Hipertensión'), ('C', 'Colesterol'), ('O', 'Otra')], help_text='Condiciones patológicas', max_length=200)),
                ('rendimiento_deficiencias', models.TextField(help_text='Rendimiento y deficiencias')),
                ('restricciones_alimentarias', models.CharField(choices=[('A', 'Alergias'), ('I', 'Intolerancias alimentarias')], help_text='Restricciones alimentarias', max_length=200)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Antropometria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_medicion', models.DateField()),
                ('peso_corporal', models.FloatField(help_text='Peso en kg')),
                ('altura', models.FloatField(help_text='Altura en cm')),
                ('imc', models.FloatField(blank=True, help_text='Índice de Masa Corporal', null=True)),
                ('perimetro_abdominal', models.FloatField(help_text='Perímetro abdominal en cm')),
                ('circunferencia_abdominal', models.FloatField(help_text='Circunferencia abdominal en cm')),
                ('pliegue_cutaneo_tricipital', models.FloatField(help_text='Pliegue cutánea triicipital en mm')),
                ('pliegue_cutaneo_subescapular', models.FloatField(help_text='Pliegue cutánea subescapular en mm')),
                ('pliegue_cutaneo_bicipital', models.FloatField(help_text='Pliegue cutánea bicipital en mm')),
                ('pliegue_cutaneo_suprailiaco', models.FloatField(help_text='Pliegue cutánea suprailiaco en mm')),
                ('circunferencia_cadera', models.FloatField(help_text='Circunferencia de la cadera en cm')),
                ('perimetro_cefalico', models.FloatField(help_text='Perímetro cefálico en cm')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('sintoma', models.CharField(choices=[('F', 'Fiebre'), ('D', 'Dolor de cabeza'), ('P', 'Pérdida de cabello'), ('O', 'Otro')], max_length=100)),
                ('descripcion', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion.paciente')),
            ],
        ),
    ]
