# Generated by Django 5.2.8 on 2025-11-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0003_paciente_alimento_agua_humedad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sintoma',
        ),
    ]
