# Generated by Django 5.2.8 on 2025-11-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0004_delete_sintoma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
