# Generated by Django 5.2.8 on 2025-11-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0005_sintoma'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivoconsulta',
            name='sintomas',
            field=models.ManyToManyField(blank=True, to='nutricion.sintoma'),
        ),
    ]
