# Generated by Django 5.2.8 on 2025-11-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0006_motivoconsulta_sintomas'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivoconsulta',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
