# Generated by Django 5.2.8 on 2025-11-29 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0007_motivoconsulta_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivoconsulta',
            name='fecha_consulta',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
