# Generated by Django 5.2.8 on 2025-11-29 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0009_habitoalimentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dietas', to='nutricion.paciente'),
        ),
    ]
