# Generated by Django 5.2.8 on 2025-11-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0010_dieta_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antropometria',
            name='circunferencia_abdominal',
            field=models.FloatField(blank=True, help_text='Circunferencia abdominal en cm', null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='circunferencia_cadera',
            field=models.FloatField(blank=True, help_text='Circunferencia de la cadera en cm', null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='perimetro_abdominal',
            field=models.FloatField(blank=True, help_text='Perímetro abdominal en cm', null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='perimetro_cefalico',
            field=models.FloatField(blank=True, help_text='Perímetro cefálico en cm', null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='pliegue_cutaneo_bicipital',
            field=models.FloatField(blank=True, help_text='Pliegue cutáneo bicipital en mm', null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='pliegue_cutaneo_subescapular',
            field=models.FloatField(blank=True, help_text='Pliegue cutáneo subescapular en mm', null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='pliegue_cutaneo_suprailiaco',
            field=models.FloatField(blank=True, help_text='Pliegue cutáneo suprailiaco en mm', null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='pliegue_cutaneo_tricipital',
            field=models.FloatField(blank=True, help_text='Pliegue cutáneo triicipital en mm', null=True),
        ),
    ]
