# Generated by Django 5.2.8 on 2025-12-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0011_alter_antropometria_circunferencia_abdominal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
